### ISSUE TITLE
Incorrect Python minimum version

### ISSUE THREAD

**Issue by SamuelWAnderson45** [conqp/mcipc#1]
Your code uses variable annotations, for example here: https://github.com/conqp/mcipc/blob/master/mcipc/query/proto/basic_stats.py#L15
That requires Python 3.6 [https://www.python.org/dev/peps/pep-0526/](https://www.python.org/dev/peps/pep-0526/)
On PyPI the minimum Python version is listed as 3.2
You probably should add `python_requires` to setup.py

**Comment by conqp** [comment]
I was not aware, that somebody published this software on PyPI.
Using `python_requires` will require me to migrate the setup py from `distutils.core` to `setuptools`.
I will look into it.

**Comment by conqp** [comment]
Migrated to `setuptools` and added `python_requires`.

**Comment by SamuelWAnderson45** [comment]
Ah I assumed you were the one to put it on PyPI. Looks good, thanks!
