### ISSUE TITLE
Query exception when server-ip is 'localhost'

### ISSUE THREAD

**Issue by larsjuhw** [conqp/mcipc#10]
If you setup a local server with `server-ip=localhost` in server.properties (127.0.0.1 does not give an error), the 'full_stats' and 'basic_stats' functions will result in an exception. Wanted to ask if there are any future plans to add support for using localhost and domains in general? Could even just make it an argument for the Client classes to specify that it's not an IP.

**Comment by conqp** [comment]
It's definitely worth fixing and I'll try to get it done on Sunday.
