### ISSUE TITLE
Can use the run command...

### ISSUE THREAD

**Issue by MeviOfDoom** [conqp/mcipc#12]
I've been trying to use run(command), but when ever I do, nothin happens. Things like client.players work fine tho...
This is my Code:

----------------------------------------
from mcipc.rcon import Client

ip="*********"
port=25575
password="********"
command="/op MeviOfDoom"
with Client(ip, port) as client:
    client.login(password)    
    client.run(command)
    players = client.players      

print(players)
-----------------------------------------
(I've been using client.players as check, if the connection works fine.)
I tried to put in the command without and with the / and I tried both of that while I used it directly where the variable command sits right now. I also tried with and without "" in client.run, even tho I couldnt see why it would work without... I'm probably just stupid and used something wrong or something like that, so I'm sorry but still thank you for your help :)

**Comment by MeviOfDoom** [comment]
Also I took indentation in account, just doesn't look like it for some GitHub reason...

**Comment by MeviOfDoom** [comment]
So I just noticed 2 things: You dont see it in the chat, if you are Op and then get Op via rcon and the second thing is that I cant use /say, but that might be a problem with the rcon command itself

**Comment by conqp** [comment]
The command you executed should work fine, although the leading forward slash is redundant when using RCON.
Also you never checked the return value of `client.run()` so how can you assume, that "nothing happens"?
Of course _something_ happened. Just investigate the return value.
Furthermore, RCON is not related to the in-game chat.
And you can also use the `say` command via RCON. Either via `client.say("text")` or the long way via `client.run("say text")`.
