### ISSUE TITLE
client.players error

### ISSUE THREAD

**Issue by SwiftCoding256** [conqp/mcipc#13]
Hey. Thats the code I use right now.
```
from mcipc.rcon import Client


with Client('myip', myport) as client:
    client.login('mypass')
    players = client.players
    mansion = client.locate('Mansion')
    print(players)
    print(mansion)

```

`AttributeError: 'NoneType' object has no attribute 'groups'`
Thats the error i get everytime.
Any ideas? Thanks!

**Comment by conqp** [comment]
Please provide the full exception traceback.

**Comment by SwiftCoding256** [comment]
Sure!

```
Traceback (most recent call last):
  File "C:/Users/Kunde/PycharmProjects/dscbot/test.py", line 10, in <module>
    players = client.players
  File "C:\Users\Kunde\PycharmProjects\dscbot\venv\lib\site-packages\mcipc\rcon\client.py", line 102, in players
    return Players.from_response(response)
  File "C:\Users\Kunde\PycharmProjects\dscbot\venv\lib\site-packages\mcipc\rcon\datastructures\players.py", line 25, in from_response
    online, max_, names = match.groups()
AttributeError: 'NoneType' object has no attribute 'groups'
```

**Comment by conqp** [comment]
It looks like the players command returns an unexpected string.
To investigate this, you can insert a print statement after line 23 in `players.py`:
```
print('DEBUG:', text)
```
In any case: Which version of Minecraft server are you using?

**Comment by SwiftCoding256** [comment]
Got this with the Debug for now:

```
DEBUG: §6Es sind §c0§6 von maximal §c20§6 Spielern online.

Traceback (most recent call last):
  File "C:/Users/Kunde/PycharmProjects/dscbot/test.py", line 10, in <module>
    players = client.players
  File "C:\Users\Kunde\PycharmProjects\dscbot\venv\lib\site-packages\mcipc\rcon\client.py", line 102, in players
    return Players.from_response(response)
  File "C:\Users\Kunde\PycharmProjects\dscbot\venv\lib\site-packages\mcipc\rcon\datastructures\players.py", line 26, in from_response
    online, max_, names = match.groups()
AttributeError: 'NoneType' object has no attribute 'groups'

Process finished with exit code 0
```

The Server runs on Version 1.15.2 Paper

**Comment by conqp** [comment]
Well, the `§c0§6` and `§c20§6` should be the respective numbers only.
I.e. `0` and `20` respectively. I don't know where these special character come from.
What does `Paper` mean with regards to the version? Is this not a vanilla Minecraft server?

**Comment by SwiftCoding256** [comment]
Right, its a replacement for Spigot.

**Comment by SwiftCoding256** [comment]
But, the others requests are working.

**Comment by conqp** [comment]
Well. This plugin obviously results in a different server response.
Unfortunately I don't have enough information on how the responses might look.
If you'd like this function to be supported on this server version, please provide the above debug output with at least two players online, so that I can infer the output format.

**Comment by SwiftCoding256** [comment]
Do you mean like this?

```
Traceback (most recent call last):
DEBUG: §6Es sind §c2§6 von maximal §c20§6 Spielern online.
  File "C:/Users/Kunde/PycharmProjects/dscbot/test.py", line 10, in <module>
    players = client.players
  File "C:\Users\Kunde\PycharmProjects\dscbot\venv\lib\site-packages\mcipc\rcon\client.py", line 102, in players
§6dev§r: §4SwiftCoding§r§f
    return Players.from_response(response)
§6obsidian§r: JustLetHerGo§f
  File "C:\Users\Kunde\PycharmProjects\dscbot\venv\lib\site-packages\mcipc\rcon\datastructures\players.py", line 26, in from_response

    online, max_, names = match.groups()
AttributeError: 'NoneType' object has no attribute 'groups'

Process finished with exit code 1
```

**Comment by conqp** [comment]
If that's the actual output with two players online, then yes.
But this would mean, that your server version does not return the player names.
This again would mean, that the respective data structure will not have the player names available.

**Comment by SwiftCoding256** [comment]
it kinda returns the playernames i guess?

**Comment by SwiftCoding256** [comment]
```
§6dev§r: §4SwiftCoding§r§f
    return Players.from_response(response)
§6obsidian§r: JustLetHerGo§f
```
Here - in the error - we got the names. I just dont get the error.

**Comment by SwiftCoding256** [comment]
So..i sorrounded it with a TryException and now it works more or less.


```
try:
    with Client('ip + port) as client:
        client.login('pass')
        players = client.players
        mansion = client.locate('Mansion')
        print(players)
        print(mansion)
except:
    print()
```

**Comment by conqp** [comment]
Please test, whether version 1.4.3 fixes this issue.

**Comment by SwiftCoding256** [comment]
For some reason my Python IDE didnt let me update it via pip...
But after some work i updated it.
It works. Thank you!
