### ISSUE TITLE
Proper documentation would be nice.

### ISSUE THREAD

**Issue by RedstonedLife** [conqp/mcipc#14]
I just won't comment. but proper documentation would be really nice. As there isn't even documentation at all

**Comment by conqp** [comment]
> I just won't comment.
Well, you just did.

> As there isn't even documentation at all
So what would you call the content of the README.md?

I am not saying that the documentation is currently poor. But this is free software that I developed in my free time and give to you for free. If I find the time, I'll write some documentation on https://readthedocs.org/.

**Comment by conqp** [comment]
Documentation is currently being developed on [readthedocs](https://mcipc.readthedocs.io/en/latest/).
You're welcome to contribute.

**Comment by gilesknap** [comment]
@conqp this library is just what I've been looking for - it is great for educating kids on python since you have typed everything and IDE auto completion becomes very handy in exploring the possibilities.

Re documentation: I have as yet been unable to work out how to use `data` and `execute` from reading the code. Could you provide a couple of hints? I would contribute to your documentation on this subject if I could get it working.

Thanks.

**Comment by gilesknap** [comment]
got data working
```data = client.data.get(TargetType.ENTITY, "@p", "Pos")```

(unfortunately the type hints can't autocomplete this)

**Comment by conqp** [comment]
Thank you for the positive feedback.
The new methods introduced with mcipc-2.0 are a bit complex.
In general, I tried to preserve the structure from the official commands.
In cases where there is a signature like

    command subcommand <value> [optional]

You'll need to run

    client.command.subcommand(value, optional=optional)

A [list of commands is available in the official Minecraft Wiki](https://minecraft.gamepedia.com/Commands#List_and_summary_of_commands).

The `execute` command is a bit special in the way, that it self-recursive. I.e. you chain execute commands.
So if you're done, you either invoke `run(command, *args)` to execute another Minecraft command with the set environment or just run the chained command by calling it with `()`.

E.g. for the command `/execute align xz` you'll run `client.execute.align('xz')()`

**Comment by gilesknap** [comment]
Thanks, that is a helpful explanation. I've been having fun with this API today. When I have some nice working examples I could add them to your docs if you think that is useful.

By the way, I find I'm doing lots of vector math and that the built in Vec3 Tuple does not make this easy. Am I missing something? At present I keep converting back and forth to another type to do transformations etc.

**Comment by conqp** [comment]
I'd appreciate any use case examples.
In all cases where the `mcipc.rcon.types.Vec3` is expected within the RCON API, you can also use `tuple` or `list` objects of legth 3 or any subclasses thereof: https://github.com/conqp/mcipc/blob/master/mcipc/rcon/functions.py#L72

**Comment by gilesknap** [comment]
OK, again thanks. I've changed my vector math class to be a Named Tuple of 3 int and it works. BUT it grates on me because pylance (linter) complains I'm passing an incompatible type :-)

**Comment by conqp** [comment]
I'll consider adjusting the type annotation to `Union[tuple, list]` then. However, the original idea was to remind the user to pass in a tuple (or list) with length 3.

**Comment by gilesknap** [comment]
I guess you need to support lists? If not then you can type hint for a 3 element Tuple only.

**Comment by conqp** [comment]
> I guess you need to support lists? If not then you can type hint for a 3 element Tuple only.

That's actually a good idea. I'll keep the list support regarding the conversion to str, but will adjust the type hints to `Tuple[float, float, float]` only.

**Comment by conqp** [comment]
Implemented in e9f663ca89432e6423fc7ea0d66881ca57c941a6.

**Comment by gilesknap** [comment]
I see that you ended up hinting Vec3 as Union[Tuple[IntOrStr, IntOrStr, IntOrStr], str], allowing for coordinates of the form '~123'

I have also found myself using float coordinates, for example for exact positioning in the teleport command. 

Is there merit in changing IntOrStr to NumOrStr = IntOrStr = Union[float, int, str] ?

**Comment by conqp** [comment]
I allowed floats for Vec2 and Vec3 in https://github.com/conqp/mcipc/commit/adcd02c3ddc28dfcc5a3bcc865740092cf2afd8c.
