### ISSUE TITLE
2.2.6 and Fillmode

### ISSUE THREAD

**Issue by gilesknap** [conqp/mcipc#15]
Upgrading to 2.2.6 causes me to see the following when calling the fill command with a Fillmode of REPLACE.
```
Traceback (most recent call last):
  File "main.py", line 34, in <module>
    setup(client)
  File "main.py", line 18, in setup
    client.fill(bounds.start, bounds.end, "air", FillMode.REPLACE)  # type: ignore
  File "/usr/lib/python3.8/typing.py", line 759, in __getattr__
    return getattr(self.__origin__, attr)
AttributeError: '_SpecialForm' object has no attribute 'REPLACE'
```

Downgrading to 2.2.5 restores correct operation.

**Comment by conqp** [comment]
After the latest type hints refactoring, you'll need to import the enumerations not from the `types` modules, but from the corresponding `enumerations` module. Or, even simpler, just from the superordinate package. E.g. `from mcipc.rcon import FillMode`

**Comment by gilesknap** [comment]
I thought I had a reasonable grasp of type hints but you are certainly going the extra mile in this project! I have changed the import as you suggest but now see this error and I don't understand (now against version 2.2.7).
```
minecraft@gknuc:~/mc-rcon-test$ pipenv run python main.py
Traceback (most recent call last):
  File "main.py", line 33, in <module>
    setup(client)
  File "main.py", line 17, in setup
    client.fill(bounds.start, bounds.end, "air", FillMode.REPLACE)
  File "/home/minecraft/.local/share/virtualenvs/mc-rcon-test-VK3-nHJN/lib/python3.8/site-packages/mcipc/rcon/je/commands/fill.py", line 18, in fill
    command.append(mode := FillMode(mode))
  File "/usr/lib/python3.8/typing.py", line 729, in __call__
    result = self.__origin__(*args, **kwargs)
  File "/usr/lib/python3.8/typing.py", line 339, in __call__
    raise TypeError(f"Cannot instantiate {self!r}")
TypeError: Cannot instantiate typing.Union
```

Also, pylance does not like my use of the enum in the call to fill and again I'm not clear what the issue is:
![image](https://user-images.githubusercontent.com/964827/103418569-29452e80-4b87-11eb-8a04-234db512e953.png)

**Comment by gilesknap** [comment]
(I'm mostly familiar with python 3.7 and note that 'Literal' is a 3.8 thing - also that there were some changes to 'Literal' for 3.9 - I have verified that I see the same errors as above using 3.9 interpreter)

**Comment by gilesknap** [comment]
I now see what the issue is - see  #17
