### ISSUE TITLE
Block States in Item

### ISSUE THREAD

**Issue by gilesknap** [conqp/mcipc#22]
I think I'd like to extend the type ITEM to include block states, so that it could for example translate to

```minecraft:acacia_button[face=up, facing=north, powered=true]```

Do you think this is sensible?

**Comment by conqp** [comment]
Generally, yes. But let's wait with the implementation until I splitted the builder subsystem from mcipc. Then we can address any further features on the new project's issue tracker.

**Comment by conqp** [comment]
Outsourced builder subsystem to: https://github.com/conqp/mcwb
