### ISSUE TITLE
Can not install via pip "No matching distribution found for mcipc"

### ISSUE THREAD

**Issue by biejay** [conqp/mcipc#27]
I want to install mcipc on Rpi3 and get this error in the console, when i try to install via `pip install mcipc`

> Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting mcipc
  Could not find a version that satisfies the requirement mcipc (from versions: )
No matching distribution found for mcipc

**Comment by conqp** [comment]
I cannot reproduce this in a virtual environment.
What Python version are you using?

**Comment by biejay** [comment]
Python 2.7.16
respectively 
Python 3.7.3

**Comment by conqp** [comment]
mcipc requires Python 3.9 now and required Python 3.8 before that.
