### ISSUE TITLE
Client.stats() (as depicted in readthedocs) refuses to work

### ISSUE THREAD

**Issue by p0t4t0sandwich** [conqp/mcipc#32]
Code:
from mcipc.query import Client

with Client('127.0.0.1', 56005) as client:
    basic_stats = client.stats()

print(basic_stats)

Triggers:
AttributeError: 'Client' object has no attribute 'stats'

**Comment by conqp** [comment]
What version of *mcipc* are you using?

**Comment by p0t4t0sandwich** [comment]
Figured out it's a problem on my end. Turns out Thonny (what I use to edit python) is only updated to python 3.7 while rcon needs 3.8.
