### ISSUE TITLE
Bedrock?

### ISSUE THREAD

**Issue by kjoyce77** [conqp/mcipc#35]
I am totally confused on this.  I see you have put a lot of work into setting up functions for Bedrock Edition.  I can't for the life of me find anything on the Internet about getting it working and I added the Java commands and they also don't seem to work.  Sorry I'm opening an issue just would love to use this if it exists.

**Comment by conqp** [comment]
That seems to be an issue with the Bedrock Edition server and is documentation and thusly has nothing to do with mcipc.
You might want to open an issue on [Mojang's issue tracker](https://bugs.mojang.com/projects/MCPE/issues/MCPE-144370?filter=allopenissues) if you experience issues with their products.
