### ISSUE TITLE
Error while attempting to run a command using RCON on a Minecraft Bedrock Server

### ISSUE THREAD

**Issue by tsc0w** [conqp/mcipc#46]
Hi, so I am currently in the process of attempting to use RCON to run some commands remotely to my Minecraft Bedrock Server, however I am getting some errrors. I am using a discord.py Discord Bot to connect to the RCON and remotely send the command. However, I am getting one of two errors:
1st Error:
Error: connect() got an unexpected keyword argument 'login'
2nd Error:
Error: BaseClient.__init__() takes 3 positional arguments but 4 were given

My code is pretty standard as I am trying to make a simple unmute command in game which has been coded onto the RCON seperately.
My code is as below. If you could please help me in potentially informing me with the issue to fix that would be more than appreciated. Thank you. Sorry if I am missing something clear, this is my first time using the library.
discord.py code (Python):
```
@tree.command(guild = discord.Object(servers), name = 'unmute', description='A command to unmute a user on the Server (ingame)') 
@app_commands.checks.cooldown(2, 15, key = lambda i: (i.guild_id, i.user.id))
@app_commands.describe(username = "The user you want to unmute on the server.")
#@app_commands.default_permissions(administrator = True)
async def unmute(interaction: discord.Interaction, username: str):
    ip = "thisserver.net"
    port = 15342
    password = "MyRCONPW"
    
    try:
        with Client(ip, port) as client:
            client.login(password)
            command = f"unmute {username}"
            response = client.run(command)
            await interaction.response.send_message(f"Unmuted: {response}")
    except Exception as e:
        await interaction.response.send_message("An error occurred while sending the command.")
        print(f"Error: {e}")
```

**Comment by conqp** [comment]
Given your code snipped, neither alleged error message makes sense.
Please provide a minimal reproducible example.

**Comment by conqp** [comment]
Closing due to lack of feedback. 
If you can provide the requested debug info, feel ree to re-open.
