### ISSUE TITLE
mcipc.rcon.exceptions.InvalidPacketStructure:

### ISSUE THREAD

**Issue by SandrinSF** [conqp/mcipc#7]
```py
from mcipc.rcon import Client

with Client('127.0.0.1', 25565) as client:

    client.say('oi')

```

whenever I try to give some input it returns this error:
mcipc.rcon.exceptions.InvalidPacketStructure: ('Invalid tail.', b'')

**Comment by conqp** [comment]
What flavour and version of Minecraft server are you using? The exception indicates exactly what it says, namely, that the server sent a packet with invalid structure, since it does not end on two NULL bytes as required by the RCON protocol.

**Comment by conqp** [comment]
I am going to close this issue due to lack of feedback.
Feel free to re-open it if you still encouter the error and when you find the time to provide the requested information.
